Use field reification to save space.
thispolo/haxe-delegates pull request #6
Opened 2023-03-23 01:49 UTC by player-03

`convertToEField` essentially re-implements a feature from the standard library, so I figure we should use that if possible.

2023-03-23 05:50 UTC, thispolo requested changes
Many thanks for doing this, no point in recreating a language feature as you said. The only reason I am requesting a change is that it's a requirement that changes such as this be merged into `dev` and not `master`

2023-03-23 13:13 UTC, player-03 commented
Looks like changing the base pulled in some other commits. I'll clean that up in a bit.

2023-03-23 23:05 UTC, player-03 commented
Ok, got rid of the intermediate commits. Do you care about whether there's a newline at the end of the file?

2023-03-24 06:48 UTC, thispolo approved these changes

2023-03-24 06:49 UTC, merged